# Site settings
title: 一亩田
description: >
  Chengdu.Shanghai. Nijmegen
  psychology.guitar.programming beginner
  

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.mashuangpsy.com" # the base hostname & protocol for your site

author:
  fullname: jekyll + daktilo
  googleplus: https://www.google.com/+MotaquillahMaddane
  github: ShuangFarmer
  twitter: ShuangFarmer
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown