# Site settings
title: 一亩田
description: >
  I am a second year research master student in Behavioural Science (basically, Psychology) in Radboud University, the Netherlands.

baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://blog.mashuangpsy.com" # the base hostname & protocol for your site

author:
  fullname: Motaquillah Maddane
  googleplus: https://www.google.com/+MotaquillahMaddane
  github: ShuangFarmer
  twitter: ShuangFarmer
  # disqus: your_disqus_username

# google_analytics: 'UA-XXXXXXXX-X'

# Build settings
markdown: kramdown